# Generated by Django 3.0 on 2019-12-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='headline',
            field=models.BooleanField(default=False),
        ),
    ]
